name: Publish Container Images

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_run:
    workflows: ["Rust"]
    types:
      - "completed"
    branches:
      - "main"
  workflow_dispatch:  # Manual trigger added

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}

jobs:
  push_to_registry:
    name: Push Docker Iimage to Registries
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Extract version number (strip 'v' prefix)
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual trigger detected. Version must be provided as an input."
            exit 1
          fi
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Debug GHCR Login
        run: |
          echo "Checking authentication for GHCR..."
          echo "${{ secrets.GH_TOKEN }}" | docker login ${{ env.GHCR_REGISTRY }} -u ${{ github.actor }} --password-stdin || echo "GHCR Login failed"

      - name: Build and Push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.DOCKERHUB_NAMESPACE }}/${{ github.event.repository.name }}:${{ env.VERSION }}

