name: Publish Container Images

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_run:
    workflows: ["Rust"]
    types:
      - "completed"
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Declare some variables
        shell: bash
        run: |
          echo "short_git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "git_branch=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Set crate version
        shell: bash
        run: |
          last_version_tag="$( git log --format="%D" | grep -Eo 'tag: v[^,]+' | head -n 1| grep -Eo 'v[^,]+' || echo "v0.0.1")"
          dirty="$(git diff --quiet || echo -- -dirty)"
          snapshot="$(git diff --quiet -- $last_version_tag || echo -SNAPSHOT)"
          rev_version="$(echo $last_version_tag$dirty$snapshot | sed -e 's/^v//')"
          echo "rev_version=$rev_version" >> "$GITHUB_ENV"
          sed -i -e "s/^version = .*/version = \"$rev_version\"/" Cargo.toml
          echo "Version set to '$rev_version'"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_NAMESPACE }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=tag
      - name: Build and Push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.DOCKERHUB_NAMESPACE }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
            ${{ env.DOCKERHUB_NAMESPACE }}/${{ github.event.repository.name }}:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true